spring.application.name=bsd

# --- CONEXIÓN A ORACLE (VM UBUNTU) ---
spring.datasource.url=jdbc:oracle:thin:@192.168.18.3:1521/FREE
spring.datasource.username=SYSTEM
spring.datasource.password=connectBSD123
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# --- DDL AUTO (IMPORTANTE) ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Configuración de Carga de Archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Seguridad (Usuario y Clave para el Login)
spring.security.user.name=admin
spring.security.user.password=bavaria2026



